<?php $n = Zend_Registry::get('config')->get('network_name')?>

<div class="wide-info">

	<h2><?php echo $n?></h2>

	<hr />

	<p><?php echo $n?> is a great place to meet new people in your area and around
		the world. It’s packed with exciting users who want to share experiences, interests and friendship.</p>
		
	<p>We bring social networking to life by allowing you to communicate, make new
		friends, share photos, maybe even date. You can also tell people about
		your interests and who you are, and play fun games that let you meet
		new people.</p>
		
	<p>You never know who you’ll find on <?php echo $n?>.</p>

</div>
