<form class="validate-ajax" action="<?php echo $this->escape($this->element->getAction()) ?>" method="<?php echo $this->escape($this->element->getMethod()) ?>" id="<?php echo $this->element->getId(); ?>">

<?php echo $this->element->identifier; ?>
<?php echo $this->element->csrf; ?>

<div class="form-group <?php echo $this->element->password1->getId();?>">
<label for="<?php echo $this->element->password1->getId();?>"><?php echo $this->element->password1->getLabel(); ?></label>
<?php echo $this->element->password1;?>
</div>

<div class="form-group <?php echo $this->element->password2->getId();?>">
<label for="<?php echo $this->element->password2->getId();?>"><?php echo $this->element->password2->getLabel(); ?></label>
<?php echo $this->element->password2;?>
</div>

<hr/>

<div class="pull-right">
<?php echo $this->element->changepass; ?>
</div>

</form>
