
<!-- The container for the uploaded files -->
<div id="files" class="files" style="display:none"><hr /></div>

<script> 
var total_uploads = 0;

$('<?php echo $this->target_element;?>').fileupload();
$('<?php echo $this->target_element;?>').fileupload('option', {
	url: '<?php echo $this->url;?>',
	dataType: 'json',
	formData: {form_unique_key: '<?php echo $this->random_string;?>'},
	maxFileSize: php_maxFileUploadSize,
	maxNumberOfFiles: php_maxImagesPerPost,
	autoUpload: true,
	acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i
    })

 
.bind('fileuploadprocessalways', function (e, data) {

		if (typeof(data.context) === 'undefined') return false;
	
        var index = data.index,
            file = data.files[index],
            node = $(data.context.children()[index]);
        
        if (file.error) {
            node.html('<p><strong><?php echo $this->translate('File not allowed or too big');?>:</strong> '+file.name+'</p>');
        }else{
        	total_uploads++;
        }
    })
    
.bind('fileuploaddone', function (e, data) {

		if (typeof(data.context) === 'undefined') return false;
		
		if (data.result == true){

	        if (total_uploads >= php_maxImagesPerPost){
	            $('.btn-file').remove();
	            return;
	        }
	
	    	$.each(data.files, function (index, file) {
	    		$('<?php echo $this->target_element;?>').append('<input type="hidden" name="myfieldname" value="myvalue" />');
	    		$(data.context.children()[index]).find('.progress-bar').css(
	    	            'width',
	    	            '100%'
	    	        );
	    		$(data.context.children()[index]).find('.progress-bar').addClass('progress-bar-success');
	        });
	        
		}else{
			$(data.context.children()[0]).html(data.result);
		}
        
    })
    
.bind('fileuploadadd', function (e, data) {

	 	$('#files').show();
	 	
		if (total_uploads >= php_maxImagesPerPost){
	        return;
	    }
    
        data.context = $('<div/>').appendTo('#files');
        $.each(data.files, function (index, file) {
            var node = $('<div/>')
                    .append($('<span/>').text(file.name))
                    .append('<div class="progress progress-striped"><div class="progress-bar"></div><div/>');
            node.appendTo(data.context);
        });
    })

.bind('fileuploadprogress', function (e, data) {

		if (typeof(data.context) === 'undefined') return false;
	
    	$.each(data.files, function (index, file) {
    		var progress = parseInt(data.loaded / data.total * 100, 10);
            $(data.context.children()[index]).find('.progress-bar').css(
    	            'width',
    	            progress + '%'
    	        );
        });
    });


</script> 