
<div class="center-text-block footerbox">
<a href="<?php echo $this->baseUrl()?>/info/page/name/about"><?php echo $this->translate('About');?></a>
&#8208;
<a href="<?php echo $this->baseUrl()?>/info/page/name/terms"><?php echo $this->translate('Terms');?></a>
&#8208;
<a href="<?php echo $this->baseUrl()?>/info/page/name/privacy"><?php echo $this->translate('Privacy');?></a>
&#8208;
<a href="<?php echo $this->baseUrl()?>/search/users/?term="><?php echo $this->translate('Search');?></a>
</div>

<hr />

<?php echo $this->render('/partial/languages.phtml');?>

<div class="center-text-block">
<small>powered by <a rel="nofollow" href="http://www.socialstrap.net" target="_blank">socialstrap</a></small>
</div>

