<div class="message-single">
	<div class="pull-left">
		<div class="avatar small pull-left">
			<a href="<?php echo $this->baseUrl().'/'.$this->message['from_name'];?>">
				<img src="<?php echo $this->GetStorageUrl('avatar').$this->message['from_user_avatar'];?>">
			</a>
		</div>
	</div>

	<div class="media-body message-body">

			<div class="pull-right">
				<span><?php echo $this->GetTimeElapsedString($this->message['message_sent_on']);?> </span>
			</div>
			
			<h5 class="media-heading">
				<a href="<?php echo $this->baseUrl().'/'.$this->message['from_name'];?>">
					<?php echo $this->message['from_screen_name'];?>
				</a>
			</h5>

		
		<div class="message-content">
			<p>
				<?php echo $this->RenderOutput($this->message['message_content'], 'message');?>
			</p>
			
			<div class="pull-right">
				<?php echo $this->partial('/partial/btn_report.phtml', array(
						'is_reported' => $this->message['is_reported'],
						'resource_owner_name' => $this->message['from_name'],
						'resource_id' => $this->message['message_id'],
						'resource_type' => 'message',
						'btn_title' => $this->translate('Report'),
						'class' => 'btn btn-default btn-xs btn-link',
						'add_report_form' => $this->add_report_form));?>

				<a data-message-id="<?php echo $this->message['message_id'];?>" class="btn btn-warning delete-message-btn btn-xs btn-link" type="button">
				<?php echo $this->translate('Delete');?>
				</a>
			</div>
		</div>
	
	</div>

	<hr />
</div>