<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title"><?php echo $this->translate('Share');?></h4>
		</div>
		<div class="modal-body">
			<label for="share_link"><?php echo $this->translate('Direct Link')?></label>
			<input class="form-control" type="text" value="<?php echo $this->direct_link?>" name="share_link" id="share_link">
		</div>
		<div class="modal-footer">
			
			<?php if (isset($this->repost_link) && $this->repost_link):?>
			<a href="<?php echo $this->repost_link?>" class="btn btn-info"><?php echo $this->translate('Share on your Wall')?></a>
			<?php endif;?>

		</div>
	</div>
</div>