<form enctype="multipart/form-data" action="<?php echo $this->escape($this->element->getAction()) ?>" method="<?php echo $this->escape($this->element->getMethod()) ?>" id="<?php echo $this->element->getId(); ?>">

<?php echo $this->element->identifier; ?>
<?php echo $this->element->csrf; ?>

<div class="form-group pull-right <?php echo $this->element->avatarfile->getId();?>">
<span class="btn btn-default btn-file">
<span><?php echo $this->element->avatarfile->getLabel(); ?></span>
<?php echo $this->element->avatarfile->render();?>
</span>
</div>

<br/>

<div class="hidden">
<span><?php echo $this->element->next; ?></span>
</div>

</form>
