<form class="validate-ajax" action="<?php echo $this->escape($this->element->getAction());?>" method="<?php echo $this->escape($this->element->getMethod());?>" id="<?php echo $this->element->getId();?>">

<?php echo $this->element->identifier; ?>
<?php echo $this->element->csrf; ?>

<div class="form-group <?php echo $this->element->content->getId();?>">
<?php echo $this->element->content; ?>
</div>

<?php if (isset($this->element->privacy)):?>
<div class="form-group <?php echo $this->element->privacy->getId();?>">
<label for="<?php echo $this->element->privacy->getId();?>"><?php echo $this->element->privacy->getLabel(); ?></label>
<?php echo $this->element->privacy; ?>
</div>
<?php endif;?>

<hr />

<div class="pull-right">
<?php echo $this->element->submitbutton; ?>
</div>

</form>
