<?php $msg = $this->element->name->getMessages();?>

<form <?php if (empty($msg)) echo 'style="display:none"'?> class="validate-ajax" action="<?php echo $this->escape($this->element->getAction()) ?>" method="<?php echo $this->escape($this->element->getMethod()) ?>" id="<?php echo $this->element->getId(); ?>">

<h4><?php echo $this->translate('Forgot Password?');?></h4>
<hr/>

<?php echo $this->element->identifier; ?>
<?php echo $this->element->csrf; ?>

<div class="form-group <?php echo $this->element->name->getId();?>">
<label for="<?php echo $this->element->name->getId();?>"><?php echo $this->element->name->getLabel();?></label>
<?php echo $this->element->name;?>
</div>

<div class="pull-left">
<button class="forgot-password btn btn-default" type="button"> &laquo; <?php echo $this->translate('Back');?></button>
</div>

<span class="pull-right"><?php echo $this->element->lostpasswordsubmit; ?></span>

</form>
