<?php echo $this->partial('/partial/images_submenu.phtml', array(
		'profile_data' => $this->profile_data,
		'total_images' => $this->total_images,
		'total_albums' => $this->total_albums,
		'action' => 'edit_album',
		'active_item' => $this->active_item,
		'active_item_id' => (isset($this->active_item_id) ? $this->active_item_id : 0)
		));?>
		
<div class="well">
	<?php echo $this->album_form;?>
</div>
