<body>

	<p>Hello <?php echo $this->screen_name; ?></p>

	<p>
		Please <a href="<?php echo $this->activation_link; ?>">Click Here</a>
		to activate your account or copy and paste this URL to your browser's address bar: <?php echo $this->activation_link; ?>
	</p>
	
	<p>
		Best regards,<br />
		Webmaster
	</p>

	<small>If you didn't sign up for our service feel free to delete this message.</small>
	
</body>

