<?php $n = Zend_Registry::get('config')->get('network_name')?>

<div class="wide-info">
	<h2>Privacy Policy</h2>

	<p><?php echo $n?> is committed to ensuring your privacy is protected. Any
		information that you provide to <?php echo $n?> by which you can be
		identified will be used only in accordance with the privacy policy
		stated below.</p>
	<p>
		<strong>Cookies:</strong><br /> The viewer may receive a cookie. A
		cookie is a small data structure sent from a web server to the
		internet browser and saved on your hard drive as a text file. Most web
		browsers are set to accept cookies. If you do not wish to receive
		cookies you can disable this function in your web browser although
		doing so may restrict access to some web pages.
	</p>
	<p>Cookies store non-personal information such as your server address,
		your top level domain name, the date and the time of your visit to the
		site, the pages you accessed and downloaded, the address of the last
		site you visited, and the type of browser you are using. We use this
		information for monitoring our web site use to facilitate web site
		management, development and planning. We use traffic log cookies to
		identify which pages are being used. This helps us analyze data about
		webpage traffic and improve our website in order to tailor it to
		customer needs. We only use this information for statistical analysis
		purposes.</p>
	<p>The only self identifying information involved in the cookies shows
		the general location where you come from, helping us to track which
		countries use the website to the greatest extent. We use third-party
		advertising companies to serve ads when you visit our website. These
		companies may use information (not including your name, address, email
		address, or telephone number) about your visits to this and other
		websites in order to provide advertisements about goods and services
		of interest to you.</p>
	<p>
		<strong>Security:</strong><br /> While <?php echo $n?> takes measures to
		ensure privacy of all information transmitted on the website,
		<?php echo $n?> is unable to guarantee secure transmission of information
		over the internet. Viewers must be aware of the risks they are taking
		in any information that they choose to submit to any website or in
		electronic mail.
	</p>
	<p>
		<strong>Links:</strong><br /> <?php echo $n?> is in no way responsible for
		websites that are linked from <?php echo $n?>, once you leave the
		<?php echo $n?> jurisdiction we are unable to ensure your privacy. The
		protection policies of the other website in question may vary greatly
		from that of <?php echo $n?>.
	</p>
	<p>
		<strong>Changes:</strong><br /> Changes may be made at any time
		according to our privacy policy. Changes will become effective
		immediately upon changes to this website. Viewers may check this
		website at anytime to be up to date on the privacy policies of
		<?php echo $n?>.
	</p>

</div>
