<?php $n = Zend_Registry::get('config')->get('network_name')?>

<div class="wide-info">
	<h2>Terms of Service</h2>
	<h3>Introduction</h3>
	<p>Welcome to <?php echo $n?>, a social media network where friends share
		their lives and explore great entertainment. <?php echo $n?> may be accessed 
		through the Internet and
		through WAP services provided by certain mobile network providers.
		By accessing or using the <?php echo $n?> Service, you signify that you have
		read the following terms and conditions (the &rsquo;Terms of
		Service&rsquo;) and accept and agree to be bound by them, whether
		or not you register with <?php echo $n?>.</p>
	<h3>Changes to <?php echo $n?> and the Terms of Service</h3>
	<p>We reserve the right, at our sole discretion, to change, modify,
		add, or delete portions of these Terms of Service at any time
		without further notice. If we do this, we will post the changes to
		these Terms of Service on this page and we may send registered
		users an email notifying you of the change. IF ANY MODIFICATION IS
		UNACCEPTABLE TO YOU, YOU SHALL STOP USING THE <?php echo $n?> SERVICE. YOUR
		CONTINUED USE OF THE <?php echo $n?> SERVICE FOLLOWING OUR POSTING OF A
		CHANGE NOTICE OR NEW AGREEMENT ON OUR SITE OR RECEIVING OUR EMAIL
		NOTIFYING YOU OF THE CHANGE WILL CONSTITUTE YOUR BINDING ACCEPTANCE
		OF THE CHANGE.</p>
	<h3>Eligibility and Registration</h3>
	<p>You should provide true, accurate and complete registration information 
		to be a <?php echo $n?>
		member (&rsquo;Member&rsquo;), and also maintain the accuracy of
		this information. As part of the registration process, you will be
		asked to select a username and password and you will be responsible
		for all activities occurring under your username and for keeping
		your password secure. We may refuse to grant you a username that
		impersonates someone else, is or may be protected by trademark or
		proprietary rights law, or is vulgar, offensive or otherwise
		inappropriate, as determined by us in our sole discretion.</p>
	<h3>Member Conduct and Appropriate Content</h3>
	<p>The <?php echo $n?> Service is made available for your personal,
		non-commercial use only. You may not use the <?php echo $n?> Service for any
		illegal or unauthorized purpose. International users agree to
		comply with all local rules regarding online conduct and acceptable
		content, including laws regulating the export of data from the
		United States or your country of residence. You are solely
		responsible for your conduct and any data, text, information,
		graphics, photos, profiles, audio and video clips, links and other
		content (&rsquo;Materials&rsquo;) that you submit, post, and
		display on the <?php echo $n?> Service.</p>
	<p>We may, but shall have no obligation to, remove or limit access
		to Materials originating from any <?php echo $n?> user that we determine in
		our sole discretion are unlawful, fraudulent, threatening,
		libelous, defamatory, obscene or otherwise objectionable, or
		infringes or violates any party&rsquo;s intellectual property or
		other proprietary rights or these Terms of Service. Further, under
		no circumstances does <?php echo $n?> have any obligation to check the
		accuracy or truthfulness of any Materials, nor to monitor any
		Member&rsquo;s use of the <?php echo $n?> Service.</p>
	<p><?php echo $n?> reserves the right to deactivate user accounts without 
		further notice.</p>
	<h3>Conditions For Use</h3>
	<p>You agree to abide by all applicable local, state, national and
		international laws and regulations and are solely responsible for
		all acts or omissions that occur under your account made by you
		including the content of your transmissions through the <?php echo $n?>
		Service. By way of example, and not as a limitation, you agree NOT
		to:</p>
	<ul>
		<li>Defame, abuse, harass, stalk, threaten or otherwise violate the
			rights (such as rights of privacy and publicity) of others.</li>
		<li>Publish, distribute and/ or disseminate any harmful, obscene,
			indecent, unlawful, libelous, profane, defamatory, infringing,
			inappropriate, hateful, or racially, ethnically or otherwise
			objectionable material or information.</li>
		<li>Use other Members' personal data for purposes other than
			establishing contact that is reasonably expected to be welcomed by
			such other Members.</li>
		<li>Submit Materials that are unlawful or promote or encourage illegal
			activity or that would violate the property rights of others.</li>
		<li>Submit Materials of any third party without such third party's
			prior written consent, or Materials that falsely express or imply
			that such Materials are sponsored or endorsed by <?php echo $n?>.</li>
		<li>Create a false or misleading identity of, including, but not
			limited to, a <?php echo $n?> employee, or falsely state or otherwise
			misrepresent your affiliation with a person or entity, for the
			purpose of misleading others as to the identity of the sender or
			the origin of a message or to harvest or otherwise collect
			information about others.</li>
		<li>Transmit, email or post any material that contains in any form
			software viruses or such programs as including but not limited to,
			Trojan horses, worms, time bombs, cancel-bots, computer code, files
			or programs designed to interrupt, destroy or limit the functionality
			of any computer software or hardware or telecommunications equipment.</li>
		<li>Use the <?php echo $n?> Service in any unlawful manner or in any other
			manner that could damage, disable, overburden or impair the
			website.</li>
		<li>Attempt to gain unauthorized access to the <?php echo $n?> Service, other
			accounts, computer systems or networks connected to the <?php echo $n?>
			Service, through password mining or any other means.</li>
		<li>Modify, adapt, translate, or reverse engineer any portion of
			the <?php echo $n?> Service, or use any robot, spider, site search/retrieval
			application, or other device to retrieve or index any portion or
			the <?php echo $n?> Service, except as expressly authorized by <?php echo $n?>.</li>
		<li>Reformat or frame any portion of the web pages that are part of
			the <?php echo $n?> Service.</li>
		<li>Upload, post or disseminate content that infringes any patent,
			trademark, trade secret, copyright, rights of privacy or publicity,
			or other proprietary right of any party or infringes any intellectual
			property law or any other applicable law.</li>
		<li>Remove any copyright, trademark or other proprietary rights
			notices contained in or on the <?php echo $n?> Service.</li>
		<li>Disseminate any unsolicited or unauthorized advertising,
			promotional materials, 'junk mail', 'spam', 'chain letters', 'pyramid
			schemes', or any other form of such solicitation.</li>
		<li>Interfere with another Member's use and enjoyment of the <?php echo $n?>
			Service.</li>
		<li>Harvest or collect email addresses or other contact information
			of Members, including names, from the <?php echo $n?> Service by
			electronic or other means.</li>
	</ul>
	<h3>Proprietary Rights</h3>
	<p><?php echo $n?> does not claim any ownership rights in any Materials that
		you submit, post, or display on or through the <?php echo $n?> Service. After
		submitting, posting or displaying Materials on or through <?php echo $n?> or
		the <?php echo $n?> Service, you continue to retain all ownership rights in
		such Materials, and you continue to have the right to use your
		Materials in any way you choose. By submitting, posting or
		displaying any Materials on or through the <?php echo $n?> Service, you
		hereby grant to <?php echo $n?> and its agents and assigns a limited license
		to use, modify, publicly perform, publicly display, reproduce, and
		distribute such Materials solely in connection with the <?php echo $n?>
		Service or the promotion thereof.</p>
	<p>Without this license, <?php echo $n?> would be unable to provide the <?php echo $n?>
		Service. For example, without the right to modify your Materials,
		<?php echo $n?> would not be able to digitally compress music files that you
		or other Members submit or otherwise format Materials to satisfy
		technical requirements, and without the right to publicly perform
		Materials, <?php echo $n?> could not allow users and Members to listen to
		music posted by Members. The license you grant to <?php echo $n?> is
		non-exclusive (meaning you are free to license your Materials to
		anyone else in addition to <?php echo $n?>), fully-paid and royalty-free
		(meaning that <?php echo $n?> is not required to pay you for the use on the
		<?php echo $n?> Service of the Materials that you post), sub licensable (so
		that <?php echo $n?> is able to use its affiliates and subcontractors such as
		Internet and WAP content delivery networks to provide the <?php echo $n?>
		Service), and worldwide (because the Internet and the <?php echo $n?> Service
		are global in reach). This license will terminate at the time you
		remove your Materials from the <?php echo $n?> Service, except that you agree
		that the license will continue solely with respect to other
		Members' continued use of your Materials that are not music or
		videos (i.e. photos or skins); provided, however if you remove any
		of the Materials from the <?php echo $n?> Service, <?php echo $n?> reserves the right
		to remove all of your Materials from other Member's pages. You agree to pay for all
		royalties, fees, and any other monies owing any person by reason of
		any Materials posted by you to or through the <?php echo $n?> Service. The
		hosting of certain items that you post, such as video, may require
		your agreement to a separate license agreement or terms of use.</p>
	<p><?php echo $n?> and its affiliates and licensors own and retain all
		rights in the <?php echo $n?> Web site and <?php echo $n?> Service, which contain
		proprietary and confidential information that is protected by
		applicable intellectual property and other laws, including without
		limitation all (1) text, (2) software, (3) photographs, (4)
		graphics, (5) page layout, and (6) design presented through and as
		part of the <?php echo $n?>. Except as expressly authorized
		by <?php echo $n?>, you may not copy, modify, publish, transmit, distribute,
		perform, display or sell any of <?php echo $n?> proprietary information.
		</p>
	<h3>Privacy &amp; Personal Information</h3>
	<p>We take your privacy very seriously and collection and use of
		personal information is governed by our Privacy Policy.</p>
	<p>Information collected in connection with your use of the <?php echo $n?>
		Service may be processed and stored in the United States, or other
		countries where <?php echo $n?> or its parent, affiliates, subsidiaries or
		service providers maintain facilities. 
		Additionally, you agree that we may use your <?php echo $n?> username to
		authenticate you on any service provided by <?php echo $n?> or its
		affiliates.</p>
	<h3>Copyright Policy</h3>
	<p>You may not post, modify, distribute, or reproduce in any way any
		copyright material, trademarks, or other proprietary information
		belonging to others without obtaining the prior written consent of
		the owner of such proprietary rights. <?php echo $n?> respects the
		intellectual property rights of others and reserves the right to
		terminate any user's access to the <?php echo $n?> Service according to these
		terms of use if <?php echo $n?> is notified that such user's activities
		infringe the rights of third parties on more than one occasion. If
		you believe that your work (or the work of a third party on whose
		behalf you are entitled to act) has been copied in a way that
		constitutes copyright infringement, please file a copyright
		infringement notification (Notice) with us, by sending a written
		communication which should include the following information, in
		the same order as is set out in (i) to (x) below:</p>
	<p>(i) statement that you have identified material on the <?php echo $n?>
		Service which infringes your copyright (or infringes the copyright
		of a third party on whose behalf you are entitled to act, if
		applicable); (ii) a description of the copyrighted work that you
		claim has been infringed, which should include the type of work
		(such as a book or a sound recording) and any relevant further
		details (such as the title and date of publication, as applicable);
		(iii) the country or countries to which your copyright applies;
		(iv) a description of the way in which the copyright material has
		been infringed; (v) a description of where the material that you
		claim is infringing is located on the <?php echo $n?> Service (including a
		URL and/or screen shot); (vi) your address, telephone number, and
		email address so that we may get in contact with you; (vii) the
		contact details that you would like us to provide to the alleged
		infringer so that they may contact you directly, in order to
		attempt to resolve the complaint; (viii) a statement by you that
		you have a good faith belief that the disputed use of the copyright
		work is not authorized by the copyright owner (or by a third party
		who is legally entitled to do so on behalf of the copyright owner)
		and is not otherwise permitted by law; (ix) a statement by you,
		made under penalty of perjury, that the above information in the
		Notice is accurate and that you are the copyright owner or
		authorized to act on the copyright owner's behalf and (x) an
		electronic or physical signature (which may be a scanned copy) of
		the copyright owner.</p>

</div>
