<?php if (isset($this->sidebar_nav_menu) && !empty($this->sidebar_nav_menu)):?>
<div class="well sidebarbox <?php if (isset($this->sidebar_nav_menu_class) && !empty($this->sidebar_nav_menu_class)) echo $this->sidebar_nav_menu_class?>">
	<ul class="nav nav-pills nav-stacked">
 		<?php foreach ($this->sidebar_nav_menu as $title => $link):?>
 		
 			<?php if ($link === 'divider'):?>
 				<li><hr /></li><?php continue;?>
 			<?php endif;?>
 			
			<li<?php if ($title == $this->sidebar_nav_menu_active_item) echo ' class="active"';?>>
				<a href="<?php echo $link?>"><?php echo $title?></a>
			</li>
		<?php endforeach;?>
	</ul>
</div>
<?php endif;?>