<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/blueimp/js/cors/jquery.postmessage-transport.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/blueimp/js/cors/jquery.xdr-transport.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/blueimp/js/vendor/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/blueimp/js/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/blueimp/js/jquery.fileupload.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/blueimp/js/jquery.fileupload-process.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/blueimp/js/jquery.fileupload-validate.js"></script>
