
<div id="lightbox-modal" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body"></div>
			<div class="modal-footer"></div>
		</div>
	</div>
</div>


<div id="confirmation-modal" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"><?php echo $this->translate('Confirm');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate('Are you sure you want to do this?');?></p>
			</div>
			<div class="modal-footer">
				<button class="btn btn-warning btn-confirm-action"><?php echo $this->translate('Yes');?></button>
				<button class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('No');?></button>
			</div>
		</div>
	</div>
</div>


<div id="share-modal" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"><?php echo $this->translate('Share');?></h4>
			</div>
			<div class="modal-body">
				<br />
			</div>
			<div class="modal-footer">
				<br />
			</div>
		</div>
	</div>
</div>


<div id="editor-modal" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"><?php echo $this->translate('Edit');?></h4>
			</div>
			<div class="modal-body">
				<br />
			</div>
		</div>
	</div>
</div>

<?php if (!$this->HasIdentity()):?>
<div id="login-modal" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<ul class="nav nav-tabs">
					<li class="active"><a href="#tab-login" data-toggle="tab"><?php echo $this->translate('Sign in');?></a></li>
					<li><a href="#tab-register" data-toggle="tab"><?php echo $this->translate('Create Account');?></a></li>
				</ul>

				<div class="tab-content" id="myTabContent">
					<div id="tab-login" class="tab-pane fade active in">
						<div class="login-box">
					<?php echo $this->modal_login_form;?>
					<?php echo $this->modal_lostpassword_form;?>
			  	</div>
					</div>
					<div id="tab-register" class="tab-pane fade">
						<div class="login-box">
				    <?php echo $this->modal_register_form;?>
				 </div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php endif;?>
