<!DOCTYPE html>
<html>
<head>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
	<meta content="socialstrap" name="generator">
	
	<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
	<!--[if lt IE 9]><script src="<?php echo $this->baseUrl()?>/include/html5shiv/dist/html5shiv.js"></script><![endif]-->
	
	<link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/images/favicon.ico" />

	<!-- jQuery -->
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/jQuery/jquery-1.11.1.min.js"></script>

	<!-- bootstrap js -->
	<script src="<?php echo $this->baseUrl()?>/bootstrap/js/bootstrap.min.js"></script>
	
	<!-- load themed css -->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap.min.css">

	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/responsive-fix.css">
	
	<!-- load standard css -->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/ie-fix.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/style.css">
	

</head>
<body>

<?php echo $this->render('_layout/topmenu.phtml');?>

<br /><br /><br />

<div class="container main">
<div class="row well">
  <div class="col-md-12">
 
	  <h1><?php echo $this->message ?></h1>
	
	  <?php if (isset($this->exception)): ?>
	  
	  <h3><?php echo $this->translate('Exception information:')?></h3>
	  <p>
	      <b><?php echo $this->translate('Message:')?></b> <?php echo $this->exception->getMessage() ?>
	  </p>
	
	  <h3><?php echo $this->translate('Stack trace:')?></h3>
	  <pre><?php echo $this->exception->getTraceAsString() ?>
	  </pre>
	
	  <h3><?php echo $this->translate('Request Parameters:')?></h3>
	  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
	  </pre>
	
	  <?php endif ?>

  </div>
</div>
</div>


<?php echo $this->render('_layout/modals.phtml');?>
</body>

</html>


 
